force-app/main/default/objects/Board__c/Board__c.object-meta.xml
<CustomObject>
    <label>Board</label>
    <nameField>
        <label>Board Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Board__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Board__c/fields/Lane__c.field-meta.xml
<CustomField>
    <fullName>Lane__c</fullName>
    <label>Lane</label>
    <referenceTo>Lane__c</referenceTo>
    <relationshipLabel>Boards</relationshipLabel>
    <relationshipName>Boards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Board__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Card__c/Card__c.object-meta.xml
<CustomObject>
    <label>Card</label>
    <nameField>
        <displayFormat>Card-{000}</displayFormat>
        <label>Card ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Card__c/fields/Board__c.field-meta.xml
<CustomField>
    <fullName>Board__c</fullName>
    <label>Board</label>
    <referenceTo>Board__c</referenceTo>
    <relationshipLabel>Cards</relationshipLabel>
    <relationshipName>Cards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Card__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <label>Color</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/X_Position__c.field-meta.xml
<CustomField>
    <fullName>X_Position__c</fullName>
    <label>X Position</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/Y_Position__c.field-meta.xml
<CustomField>
    <fullName>Y_Position__c</fullName>
    <label>Y Position</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lane__c/Lane__c.object-meta.xml
<CustomObject>
    <label>Swim Lane</label>
    <nameField>
        <label>Lane Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Swim Lanes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Lane__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lane__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Lane_User__c/Lane_User__c.object-meta.xml
<CustomObject>
    <label>Swim Lane User</label>
    <nameField>
        <displayFormat>LU-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Swim Lane Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lane_User__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Lane_User__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When this is checked, a Swim Lane user can access this Swim Lane.</description>
    <inlineHelpText>When this is checked, a Swim Lane user can access this Swim Lane.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lane_User__c/fields/Lane__c.field-meta.xml
<CustomField>
    <fullName>Lane__c</fullName>
    <label>Lane</label>
    <referenceTo>Lane__c</referenceTo>
    <relationshipLabel>Lane Users</relationshipLabel>
    <relationshipName>Lane_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/test/default/classes/KickboardCtrlTest.cls
@isTest
public class KickboardCtrlTest {
    @TestSetup
    static void createData() {
        Lane__c lane = new Lane__c(Name = 'Test Lane');
        insert lane;
        Board__c board = new Board__c();
        board.Name = 'Test Board';
        board.Order__c = 1;
        board.Lane__c = lane.Id;
        insert board;
        System.runAs(new User(Id = UserInfo.getUserId())) {
            PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'Kickboard_User'];
            insert new PermissionSetAssignment(AssigneeId = UserInfo.getUserId(), PermissionSetId = ps.Id);
        }
    }

    @IsTest
    static void checkBoardRetrieval() {
        Lane__c l = [SELECT Id FROM Lane__c];
        Test.startTest();
        List<Board__c> boards = KickboardCtrl.getBoards(l.Id);
        system.assertEquals(1, boards.size());
        Test.stopTest();
    }

    @IsTest
    static void checkCardCreation() {
        Board__c b = [SELECT Id FROM Board__c];
        Test.startTest();
        System.runAs(new User(Id = UserInfo.getUserId())) {
            List<Card__c> cards = KickboardCtrl.getCards(b.Id);
            system.assertEquals(0, cards.size());

            Card__c card = KickboardCtrl.createNewCard(b.Id, null, null, null);
            system.assertEquals(0, card.X_Position__c);
            system.assertEquals(0, card.Y_Position__c);

            card = KickboardCtrl.createNewCard(b.Id, 2, 3, null);
            system.assertEquals(2, card.X_Position__c);
            system.assertEquals(3, card.Y_Position__c);

            cards = KickboardCtrl.getCards(b.Id);
            system.assertEquals(2, cards.size());
        }
        Test.stopTest();
    }

    @IsTest
    static void checkCardUpdates() {
        Board__c b = [SELECT Id FROM Board__c];
        Card__c card = KickboardCtrl.createNewCard(b.Id, null, null, null);
        Test.startTest();

        KickboardCtrl.saveCard(card.Id, 'demo', null, null, null, null);
        card = [
            SELECT Id, X_Position__c, Y_Position__c, Description__c, Color__c
            FROM Card__c
            WHERE Id = :card.Id
        ];
        system.assertEquals('demo', card.Description__c);
        system.assertEquals('yellow', card.Color__c);

        KickboardCtrl.saveCard(card.Id, null, 2, 3, null, null);
        card = [
            SELECT Id, X_Position__c, Y_Position__c, Description__c, Color__c
            FROM Card__c
            WHERE Id = :card.Id
        ];
        system.assertEquals(2, card.X_Position__c);
        system.assertEquals(3, card.Y_Position__c);

        KickboardCtrl.saveCard(card.Id, null, null, null, 'blue', null);
        card = [
            SELECT Id, X_Position__c, Y_Position__c, Description__c, Color__c
            FROM Card__c
            WHERE Id = :card.Id
        ];
        system.assertEquals('blue', card.Color__c);

        Test.stopTest();
    }

    @IsTest
    static void checkCardDelete() {
        Board__c b = [SELECT Id FROM Board__c];
        Card__c card1 = KickboardCtrl.createNewCard(b.Id, null, null, null);
        Card__c card2 = KickboardCtrl.createNewCard(b.Id, 2, 3, null);

        Test.startTest();
        System.runAs(new User(Id = UserInfo.getUserId())) {
            List<Card__c> cards = KickboardCtrl.getCards(b.Id);
            system.assertEquals(2, cards.size());

            KickboardCtrl.deleteCard(card1.Id);

            cards = KickboardCtrl.getCards(b.Id);
            system.assertEquals(1, cards.size());

            KickboardCtrl.deleteCard(card2.Id);

            cards = KickboardCtrl.getCards(b.Id);
            system.assertEquals(0, cards.size());
        }
        Test.stopTest();
    }

    @IsTest
    static void checkSessionId() {
        Test.startTest();
        String sessionId = KickboardCtrl.getSessionId();
        system.assert(sessionId != null);
        Test.stopTest();
    }

    @IsTest
    static void checkInactiveGuestInvite() {
        Lane__c lane = [SELECT Id, Code__c FROM Lane__c];

        Lane_User__c lu = new Lane_User__c();
        lu.Email__c = 'test@test.com';
        lu.Lane__c = lane.Id;
        lu.Is_Active__c = false;
        insert lu;

        Test.startTest();
        System.runAs(new User(Id = UserInfo.getUserId())) {
            Id inviteeId = KickboardCtrl.isValidCredentials(lane.Id, null, null);
            system.assertEquals(null, inviteeId);

            inviteeId = KickboardCtrl.isValidCredentials(
                lane.Id,
                'test@example.com',
                null
            );
            system.assertEquals(null, inviteeId);

            inviteeId = KickboardCtrl.isValidCredentials(lane.Id, null, '12345678');
            system.assertEquals(null, inviteeId);

            inviteeId = KickboardCtrl.isValidCredentials(
                lane.Id,
                'test@example.com',
                '12345678'
            );
            system.assertEquals(null, inviteeId);

            inviteeId = KickboardCtrl.isValidCredentials(
                lane.Id,
                'test@test.com',
                null
            );
            system.assertEquals(null, inviteeId);

            inviteeId = KickboardCtrl.isValidCredentials(
                lane.Id,
                null,
                lane.Code__c
            );
            system.assertEquals(null, inviteeId);

            inviteeId = KickboardCtrl.isValidCredentials(
                lane.Id,
                'test@test.com',
                '12345678'
            );
            system.assertEquals(null, inviteeId);

            inviteeId = KickboardCtrl.isValidCredentials(
                lane.Id,
                'test@example.com',
                lane.Code__c
            );
            system.assertEquals(null, inviteeId);

            inviteeId = KickboardCtrl.isValidCredentials(
                lane.Id,
                'test@test.com',
                lane.Code__c
            );
            system.assertEquals(null, inviteeId);
        }
        Test.stopTest();
    }

    @IsTest
    static void checkActiveGuestInvite() {
        Lane__c lane = [SELECT Id, Code__c FROM Lane__c];

        Lane_User__c lu = new Lane_User__c();
        lu.Email__c = 'test@test.com';
        lu.Lane__c = lane.Id;
        lu.Is_Active__c = true;
        insert lu;

        Test.startTest();
        System.runAs(new User(Id = UserInfo.getUserId())) {
            Id inviteeId = KickboardCtrl.isValidCredentials(lane.Id, null, null);
            system.assertEquals(null, inviteeId);

            inviteeId = KickboardCtrl.isValidCredentials(
                lane.Id,
                'test@example.com',
                null
            );
            system.assertEquals(null, inviteeId);

            inviteeId = KickboardCtrl.isValidCredentials(lane.Id, null, '12345678');
            system.assertEquals(null, inviteeId);

            inviteeId = KickboardCtrl.isValidCredentials(
                lane.Id,
                'test@example.com',
                '12345678'
            );
            system.assertEquals(null, inviteeId);

            inviteeId = KickboardCtrl.isValidCredentials(
                lane.Id,
                'test@test.com',
                null
            );
            system.assertEquals(null, inviteeId);

            inviteeId = KickboardCtrl.isValidCredentials(
                lane.Id,
                null,
                lane.Code__c
            );
            system.assertEquals(null, inviteeId);

            inviteeId = KickboardCtrl.isValidCredentials(
                lane.Id,
                'test@test.com',
                '12345678'
            );
            system.assertEquals(null, inviteeId);

            inviteeId = KickboardCtrl.isValidCredentials(
                lane.Id,
                'test@example.com',
                lane.Code__c
            );
            system.assertEquals(null, inviteeId);

            inviteeId = KickboardCtrl.isValidCredentials(
                lane.Id,
                'test@test.com',
                lane.Code__c
            );
            system.assertEquals(lu.Id, inviteeId);
        }
        Test.stopTest();
    }

    @IsTest
    static void checkExportLane() {
        Lane__c lane = [SELECT Id FROM Lane__c];
        Test.startTest();
        System.runAs(new User(Id = UserInfo.getUserId())) {
            String output = KickboardCtrl.exportLaneJSON(lane.Id);
            system.assertNotEquals(null, output);
        }
        Test.stopTest();
    }
}