force-app/main/default/objects/Card__c/Card__c.object-meta.xml
<CustomObject>
    <label>Card</label>
    <nameField>
        <displayFormat>Card-{000}</displayFormat>
        <label>Card ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Card__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <label>Color</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/Last_Modified_By_Guest__c.field-meta.xml
<CustomField>
    <fullName>Last_Modified_By_Guest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last Modified By (Guest)</label>
    <referenceTo>Lane_User__c</referenceTo>
    <relationshipLabel>Cards (Last Modified By (Guest))</relationshipLabel>
    <relationshipName>Cards1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/X_Position__c.field-meta.xml
<CustomField>
    <fullName>X_Position__c</fullName>
    <label>X Position</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/Y_Position__c.field-meta.xml
<CustomField>
    <fullName>Y_Position__c</fullName>
    <label>Y Position</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/KickboardWithoutSharingCtrl.cls
/**
 * This without sharing class deals with updating and deleting cards,
 * becuase a guest user does not have permissions to edit and delete records.
 */
public without sharing class KickboardWithoutSharingCtrl {
    @AuraEnabled
    public static void saveCard(
        String cardId,
        String description,
        Integer xPos,
        Integer yPos,
        String color,
        String guestUserId
    ) {
        try {
            Card__c c = new Card__c(Id = cardId);
            if (description != null) {
                c.Description__c = description;
            } else if (xPos != null && yPos != null) {
                c.X_Position__c = xPos;
                c.Y_Position__c = yPos;
            } else if (color != null) {
                c.Color__c = color;
            }

            if (!String.isBlank(guestUserId)) {
                c.Last_Modified_By_Guest__c = guestUserId;
            }
            update c;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void deleteCard(String cardId) {
        try {
            delete ([SELECT Id FROM Card__c WHERE Id = :cardId]);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}